Muskansahuincredible/StudyNotion-An-Online-Education-Platform

package-lock.json, package.json, src/App.js, src/components/GoToTop.jsx
Fixes #20 
Hey @techmannih I have added Go-To-Top button to the website which look stunning matching the website theme.
please take a look and review it, Thank you for the opportunity.
=> Added "Go-To-Top" Button to the website

src/data/homepage-explore.js
fixex #27
added relavent description in different courses
=> added discription in diffferent courses

README.md
Adding a Installation and Setup Guide.
#29 
- [] Documentation update
- [] I have performed a self-review of my code
- [] I have read and followed the Contribution Guidelines.
- [] I have tested the changes thoroughly before submitting this pull request.
- [] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.
=> add installation guide

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml, .github/ISSUE_TEMPLATE/refactor.yml, .github/ISSUE_TEMPLATE/task-request.yml
#22 
I have added all the types of templates for different kinds of issues in .github directory.
=> Added issue template

.github/workflows/autocomment-iss-close.yml
Fixes #46 
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.
=> added workflow as per issue #46

src/components/common/Footer.jsx, src/components/common/Navbar.jsx
=> added hover effects on login and sign up page issue#100 and added hover effect in social media logos issue#101

src/components/core/HomePage/CourseCard.jsx, src/components/core/ViewCourse/VideoDetailsSidebar.jsx
=> Spelling correction

src/components/core/HomePage/CourseCard.jsx
Solved issue #116 
Add hover effect to cards and card content to enhance its visual appeal.
- Feature enhancement
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/97687618/165b08c9-243f-4972-ad9a-487187d67aa0
=> Adding hover effect on cards

src/components/common/ReviewSlider.jsx
The cards in this review section are uneven and not a fixed size. 
The cards in this review section are uneven and not a fixed size. I have modified the cards to have a fixed size, which improves the UI.
**Old Design:**
**New Design:**
No response.
=> Reviews from other leaners card has been designed as even size. 

src/components/core/HomePage/ExploreMore.jsx, src/data/homepage-explore.js
issue #118 resolved
i request the admins @Muskansahuincredible & @techmannih to merge my PR and label it
I have added the hover element on power of code section on the cards 
Added hover on the card content
Changed the content of few cards wrt heading
Card Content Changed
Hover 
=> Hover effect & card content changed

public/index.html, src/components/core/HomePage/ExploreMore.jsx, src/index.js
#109 
The screen named "Unlock the power of code" section was not responsive for mobile, but now it is fully responsive on mobile screens.
---
@Muskansahuincredible Thank you for considering this enhancement . I eagerly await your feedback.
=> Bug fixes in small screen-size of mobile--Full Responsive

src/pages/Home.jsx
=> correct sentence

src/pages/ForgotPassword.jsx
=> correct submit spelling

Create Contributing.md
Fixes #139 
Addied Important point to keep in mind before starting
adding Commit Message Guidelines using Commitlint
=> Updating contributing.md

Create Contributing.md
closes #156 
The name of the repository was wrong in most places in the create_contributing.md file. Corrected it.
=> Update Create Contributing.md

package-lock.json, package.json, src/components/common/Footer.jsx, src/components/common/ReviewSlider.jsx, src/components/core/Catalog/CourseSlider.jsx
none
I hovered the social media icons with different colors and fixed some errors.
- [x ] Feature enhancement
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
please label …
=> hover with different colors

package-lock.json, package.json, public/index.html, src/App.css, src/App.js, src/components/common/BackToTop.jsx, src/components/common/ReviewSlider.jsx, src/components/core/Catalog/CourseSlider.jsx
#136 
Added a smooth scroll-activated 'Back to Top' button to enhance user experience on the website. The button is triggered when users scroll down the page, providing a convenient way to navigate back to the top without manually scrolling.
- Changes Made:
1. Implemented a 'Back to Top' button with smooth scroll activation.
2. Added transition effects for a seamless user experience.
3. Integrated JavaScript functionality to detect scroll position and display the button accordingly.
4. Ensured compatibility across different browsers for consistent behavior.
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/146121869/e20c94c1-f7c5-4a32-a9d2-4be9821e468a
.
=> Added Smooth Scroll-Activated 'Back to Top' Button for Enhanced User Experience

package-lock.json, package.json, src/App.js, src/components/common/Footer.jsx, src/pages/privacypolicy.jsx, src/pages/terms and conditions.jsx
closes #194 
Hey @Muskansahuincredible and @techmannih  I have added Privacy Policy and Terms and Conditions Pages in footer section pls take a look and review it thank you!
=> Added Legal Pages: "Privacy Policy" and "Terms and Conditions"

server/package-lock.json, server/package.json, src/components/core/Auth/Template.jsx, src/components/core/HomePage/Button.jsx
Fixes #174 
Removed the white space under the login screen, and added hover effect to the navbar
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/138088550/abe144ae-8613-4edf-91e7-239b574126f1
=> Fixes #174

package-lock.json, package.json, server/package.json, src/components/core/AboutPage/Stats.jsx
Fixes Issue #190 
1.Updated the newer version of "@babel/plugin-proposal-private-property-in-object" as it causes the problem
2. Animated the count with the animation of Counting the numbers till the end number of StatsComponent.
- [✅] Feature enhancement
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/134155725/b4636db6-be27-44ca-966e-1830a6c67e0b
- [✅] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅] I have commented my code, particularly in …
=> Add counting animation in of StatsComponent

package-lock.json
#213
I have checked the website there is no hover effects on login button as well as in footer social media icons, due to which it doesn't looks good. Please assign me this task under gssoc'24.
#213 
BUG REPORT :- Hover effect on Login button as well as footer social media icons. 
Before :- 
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/136844498/a296338a-41a9-4287-9567-c272c522c539
After :- 
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/136844498/7ba6e7d3-2a31-461a-8d6a-2f3a4e73a7ce
=> Hover effect on Login button as well as footer social media

package-lock.json, package.json, src/components/common/Footer.jsx, src/components/common/ReviewSlider.jsx, src/components/core/Catalog/CourseSlider.jsx
#153 
Added the contribute link under the community headline
on clicking it, user gets directed to studynotion repo
=> Added the "Contribute" link

package-lock.json, src/components/common/FAQ.jsx, src/pages/Home.jsx
Closes issue #183 
Added FAQ section to the website, which is also mobile friendly.
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/121669832/cee22c7e-b564-4fda-b13e-6a5aaf1aa60a
Mobile view:
Please check it and let me know if any changes to be made, Thank you!
=> Feat: Added FAQ section.

README.md
Fixed issue #152 
Added setup guideline for project which contains the integration of .env file variables for mongodb, cloudinary, nodemailer, razorpay, etc in readme like below - 
Also solves the OTP related issues through mail.
=> Added project SetUp guideline

src/components/ContactPage/ContactForm.jsx
Small Grammatical error
changes "got a idea" to "got an idea"
=> Grammatical error Fixed

src/App.js, src/components/common/Navbar.jsx
-fixes #249
- Implemented text hover on all Navbar Links.
- Resolved issue #249 
- [ ✅] Feature enhancement
https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/115502017/8a5edaf0-7106-4528-937a-0f1d2ffd6f87
- [✅] I have performed a self-review of my code
- [✅] I have read and followed the Contribution Guidelines.
- [✅]  I have tested the changes thoroughly before submitting this pull request.
- [✅]  I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅]  I have commented my code, particularly in hard-to-understand areas.
[Include any additional information or …
=> NavBar Hover effect updated

src/components/common/Navbar.jsx
Fixed #266 
I fixed the problem with the navbar which wasn't fixed.
- [X ] Feature enhancement
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
=> Fix : (Navbar Sticked)

src/components/common/Navbar.jsx
#251 solved
Made the navbar sticky on top
[StickyNavbar.webm](https://github.com/user-attachments/assets/bfe260b0-d50e-43db-9daa-2283c625a8ae)
=> Made navbar sticky on top

src/components/common/Footer.jsx
- fixes  #235 
- Added Instagram and LinkedIn accounts at footer 
- [ ✅ ] Feature enhancement
- [✅] I have performed a self-review of my code
- [✅] I have read and followed the Contribution Guidelines.
- [✅] I have tested the changes thoroughly before submitting this pull request.
- [✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅] I have commented my code, particularly in hard-to-understand areas.
=> Instagram and LinkedIn accounts at footer added

src/components/core/HomePage/CourseCard.jsx
#252 
Fixed this section to have a uniform look on all devices
=> Fixed the unlock the power section for mobile screen size

src/components/common/Navbar.jsx
Issue #280
Added hover styles to navbar links ( scale, hover color and underline animation) 
=> Navbar hover styles

src/components/common/Navbar.jsx, src/data/navbar-links.js
issue #282 
Added rate us to navbar-links.js
=> Rate us navbar

src/components/common/Navbar.jsx, src/index.css
Fixes #285 
I've added css styling in the necessary parts.
- [ ✅] Bug fix
- [ ✅] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [✅ ] I have provided relevant issue numbers after making the changes.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
=> Navbar made sticky

src/components/common/Navbar.jsx
Issue #281 
Changed styles+ hover styles of the buttons present in navbar (login and signup)
=> Login button UI

src/App.css, src/components/common/Navbar.jsx
Fixes #289 
Edited a few thing which were responsible for overriding the sticky effect of navbar, Also fixed the top white space area that appears on page during loading effect.
=> Navbar sticky

src/App.css, src/components/common/ReviewSlider.jsx, src/pages/About.jsx, src/pages/Contact.jsx, src/pages/Home.jsx
#293 
Added responsivity in the review slider,
Adjusted the margins padding and styles
Adjusted the rating bar
Changed the heading "reviews from other learners" to "happy and satisfied learners" to all pages
- [x I have tested the changes thoroughly before submitting this pull request.
<!- [X] - put a cross/X inside [] to check the box -->
=> Updating review section

src/components/core/Auth/Template.jsx
#294 
found the issue causing scroll to be disabled in login and signup page, removed the overflow-hidden property from template.jsx Both login and sign up pages are now properly responsive
=> Login page scroll

src/App.css, src/pages/Contact.jsx, src/pages/Rateus.jsx, src/pages/rateus.css
Issue #291 
Added styles to the page similar to the rest of the pages Added "Please enter field" span fields that show up when submission is done when field is blank Added an alert for acknowledgment of submission
Added footer to the page
Added the contact details box to the page as it looked pretty bland
=> Rate us page

src/pages/Rateus.jsx
#301 
Added review swiper to rate us page
<! -- [X] - put a cross/X inside [] to check the box -->
=> Added review to rate us page

src/pages/Rateus.jsx
issue #308
Fixed the bug, now on hovering on one star, the preceding stars also turn yellow as expected
=> Stars- Rate us

README.md
[DOCS] : Adding a Installation and Setup Guide.
#29 
- [] Documentation update
- [] I have performed a self-review of my code
- [] I have read and followed the Contribution Guidelines.
- [] I have tested the changes thoroughly before submitting this pull request.
- [] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.
=> [DOCS] : Adding a Installation and Setup Guide.

src/App.js
#313 
Added project to app.js with correct path links 
=> Issue #313

package-lock.json, package.json, src/App.js, src/components/common/Navbar.jsx, src/components/common/progess.css, src/components/common/progressbar.jsx, src/pages/Home.jsx
@Agarwalvidu Please merge this pr.
=> Resolved issue #322

src/components/common/BackToTop.jsx
@Agarwalvidu Pleae merge this.
=> Added scroll to Top button #315

src/components/common/Footer.jsx
Please merge this pr.
@Agarwalvidu
=> Resolved Issue #314

src/pages/Rateus.jsx, src/pages/rateus.css
#327 
The rateus.css was overwriting styles, fixed it and also edited the gap value
=> Fixed mobile view of page

src/components/common/FAQ.jsx, src/components/common/Footer.jsx, src/components/common/ReviewSlider.jsx, src/components/core/HomePage/InstructorSection.jsx, src/components/core/HomePage/LearningLanguageSection.jsx, src/pages/About.jsx, src/pages/Rateus.jsx
#320
Added hover effect for icon and regenerated link tags
- [ X] Feature enhancement
- [ X] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
=> Designs added

src/pages/Project.jsx
#334 
Fixed footer of project page
=> Footer- project page

src/components/ContactPage/ContactDetails.jsx, src/components/ContactPage/ContactForm.jsx
Issue #328 solved
- Fixed the grammatical errors: "Chat With Us" instead of "Chat On Us" and "Got an Idea" instead of "Got a Idea".
- Enhanced the contact links: clicking on the phone number and email id redirects to 'calling' and 'mailto'
[updatedContactPage.webm](https://github.com/user-attachments/assets/ef93373d-375f-4c81-941b-5c6d5008e053)
=> Updated Contact page

src/App.css
@Agarwalvidu Please merge this pr
=> Resolved Issue #343

package-lock.json, src/App.js
=> Solved Frontend error

src/data/footer-links.js
=> solved footer issue

src/components/common/Footer.jsx
=> Corrected the padding at footer

src/components/common/Navbar.jsx
=> Added some spacing between the elements in the navbar.

src/App.css, src/components/ContactPage/ContactUsForm.jsx, src/components/core/AboutPage/ContactFormSection.jsx
Issue #354 solved
- Updated the phone number input field in ContactusForm on contact page and about page.
- Fixed the grammatical error in the form on about page: "hear from you." instead of "here for you,"
[updatedPhoneNumberInput.webm](https://github.com/user-attachments/assets/c6b1c168-1cde-49bd-8ce5-cbf44b7ecec1)
=> Updated Phone number input in ContactUsForm

src/components/ContactPage/ContactDetails.jsx, src/pages/Rateus.jsx, src/pages/rateus.css
=> Modified Rate us page

src/App.css, src/components/common/Navbar.jsx
@Agarwalvidu Please merge this.
=> Resolved Issue #347

src/components/core/HomePage/InstructorSection.jsx
=> Fixed "Become an instructor " portion in Mobile view

package-lock.json, package.json, src/components/common/Footer.jsx
@Agarwalvidu Please merge this.I have added filling animation on social icon son footer section.
=> Resolved Issue #367

src/components/common/Footer.jsx
=> Fixed Footer

src/App.css, src/components/common/BackToTop.jsx
=> Fixed BackToTop

src/App.css, src/App.js, src/components/common/BackToTop.jsx
=> Fixed Whitespace

src/App.css, src/App.js, src/components/common/BackToTop.jsx, src/components/common/Navbar.jsx
=> Fixed width of Signup button in mobile responsiveness

src/App.css, src/App.js, src/components/common/BackToTop.jsx, src/components/common/Navbar.jsx
=> Added an ease out animation

src/App.css, src/components/common/Footer.jsx
=> fixed css of footer

src/App.js, src/pages/Chatbot.jsx, src/pages/Rating.css
@Agarwalvidu Please merge this.
=> Resolved Issue #400

src/pages/Chatbot.jsx
@Agarwalvidu Please merge this.
=> Added more  related questions in functionality of Chatbot. Issue No .400

src/components/core/HomePage/ExploreMore.jsx
Issue #410 solved
Made the explore more section in the home page responsive.
Before:
After:
=> Made Home Page Content Mobile Responsive

src/App.css, src/pages/Project.jsx
Issue #415 solved
Enhanced the mobile responsiveness for project page.
=> Fixed Mobile Responsiveness for Project Page

src/App.js, src/components/common/ConfirmationModal.jsx, src/components/core/Dashboard/Sidebar.jsx, src/pages/Dashboard.jsx
Made Instructor and Student dashboard responsive -
I have made the above dashboard page responsive .
=> DashBoard Update

package-lock.json, src/App.js, src/pages/Chatbot.jsx
Fixed the issue of rendering chatbot conversation "How can i help, you ?"
As user clicks on chatbot it renders immediately "How can i help, you ?" not after any question is asked.
=> Chat bot Utilization

src/App.js, src/components/common/BackToTop.jsx
Back to Top button was not working properly.
=> Fixed Back to top  working

src/App.js, src/components/common/Footer.jsx
Issue #416 solved
Made footer mobile responsive.
=> Made Footer Mobile Responsive

src/pages/Chatbot.jsx
@Agarwalvidu Please merge this.
=> Adding local storage in chatbot Isssue No.#400
